import type { Metadata } from "next";
import "../globals.css";
import fonts from "@/public/assets/fonts";
import Sidebar from "./components/sidebar";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#ECE7E0] ${fonts.satoshiMedium.variable} ${fonts.satoshiLight.variable} antialiased`}
      >
        <div className="w-full h-screen flex p-5">
          {/* Sidebar */}
          <Sidebar />

          <div className="flex-1">
            {/* Header */}
            <div className="pl-5">
              <Header />
            </div>
            {/* Content */}
            <div className="pl-5 pt-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
