import type { Metadata } from "next";
import "../globals.css";
import fonts from "@/public/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.satoshiMedium.variable} ${fonts.satoshiLight.variable} antialiased p-6`}
      >
        {children}
      </body>
    </html>
  );
}
